config/routes.rb
Rails.application.routes.draw do
    get 'sessions/new'

    root 'static_pages#main'
    get  '/help',    to: 'static_pages#help'
    get  '/main',    to: 'static_pages#main'

    get  '/signup',  to: 'users#new'
    post '/signup',  to: 'users#create'

    get '/login', to: 'sessions#new'
    post   '/login',   to: 'sessions#create'
    delete '/logout',  to: 'sessions#destroy'

    get '/courses', to: 'others#courses'
    get '/instructors', to: 'others#instructors'
    get '/subjects', to: 'others#subjects'
    get '/search', to: 'others#search'

    get '/searchCourse', to: 'users#searchCourse'
    # get  '/signin',  to: 'users#old'
    resources :users
    resources :enrollments, only: [:create, :destroy]
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/course.rb
class Course < ApplicationRecord
    has_many :passive_enrollments, class_name: 'Enrollment',
                                   foreign_key: 'course_id',
                                   dependent:   :destroy
    has_many :takingusers, through: :passive_enrollments, source: :user
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
    belongs_to :user, class_name: 'User'
    belongs_to :course, class_name: 'Course'
    validates :user_id, presence: true
    validates :course_id, presence: true
end

app/models/instructor.rb
class Instructor < ApplicationRecord
end

app/models/subject.rb
class Subject < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email = email.downcase }
    validates :name, presence: true, length: { maximum: 50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 },
                      format: { with: VALID_EMAIL_REGEX },
                      uniqueness: { case_sensitive: false }
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }

    # Returns the hash digest of the given string.
    def self.digest(string)
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                      BCrypt::Engine.cost
        BCrypt::Password.create(string, cost: cost)
    end

    has_many :active_enrollments, class_name: 'Enrollment',
                                  foreign_key: 'user_id',
                                  dependent:   :destroy
    has_many :takingcourses, through: :active_enrollments, source: :course

    def enroll(course)
        takingcourses << course
    end

    def unenroll(course)
        takingcourses.delete(course)
    end

    def enroll?(course)
        takingcourses.include?(course)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    include SessionsHelper
end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
    def create
        course = Course.find(params[:course_id])
        current_user.enroll(course)
        redirect_to current_user
     end

    def destroy
        course = Enrollment.find(params[:id]).course
        current_user.unenroll(course)
        redirect_to current_user
    end
end

app/controllers/others_controller.rb
class OthersController < ApplicationController
    def courses
        @courses = Course.all
    end

    def subjects
        @subjects = Subject.all
    end

    def instructors
        @instructors = Instructor.all
    end

    def search
        @subjects = Subject.all
    end

    def searchCourse
        course = params[:course]
        subject = params[:subject]
        if !subject.eql?('Filter by Subjects')
            @courses = Course.where(name: course).where(subject: subject)
        else
            @courses = Course.where(name: course)
        end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end

    def create
        user = User.find_by(email: params[:session][:email].downcase)
        if user && user.authenticate(params[:session][:password])
            log_in user
            redirect_to user
        else
            flash.now[:danger] = 'Invalid email/password combination' # Not quite right!
            render 'new'
        end
    end

    def destroy
        log_out
        redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
    def main
    end

    def help
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @user = User.find(params[:id])
        @courses = @user.takingcourses
    end

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            log_in @user
            flash[:success] = 'Welcome to the Course Catalog!'
            redirect_to @user
        else
            render 'new'
        end
  end

    def searchCourse
        @user ||= User.find_by(id: session[:user_id])
        course = params[:course]
        subject = params[:subject]
        if !subject.eql?('Filter by Subjects')
            @searchcourses = Course.where(name: course).where(subject: subject)
        else
            @searchcourses = Course.where(name: course)
        end
    end

    private

    def user_params
        params.require(:user).permit(:name, :email, :password,
                                     :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def full_title(page_title = '')
        base_title = 'Ruby on Rails Tutorial Sample App'
        if page_title.empty?
            base_title
        else
            page_title + ' | ' + base_title
        end
   end
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/helpers/others_helper.rb
module OthersHelper
    # load subjects from json file
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def log_in(user)
        session[:user_id] = user.id
     end

    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
  end

    def logged_in?
        !current_user.nil?
   end

    def log_out
        session.delete(:user_id)
        @current_user = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
    # Returns the Gravatar for the given user.
    def gravatar_for(user)
        gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
        image_tag(gravatar_url, alt: user.name, class: 'gravatar')
    end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">

    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Main", root_path %></li>
        <li><%= link_to "Help", help_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Home", current_user %></li>
          <li><%= link_to "Subjects", subjects_path %></li>
          <li><%= link_to "Courses", courses_path %></li>
          <li><%= link_to "Instructors", instructors_path %></li>
          <li><%= link_to "Search", search_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Settings", '#' %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_rails_default.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag    'application', media: 'all',
                                          'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
       <div class="alert alert-<%= message_type %>"><%= message %></div>
     <% end %>
      <%= yield %>
       <%= render 'layouts/footer' %>
    <!--   <%= debug(params) if Rails.env.development? %> -->
    </div>
  </body>
</html>

app/views/others/courses.html.erb
<h1>Courses</h1>
<p>
<div class="table-responsive">
  <table class="table table-striped">
                 <thead>
                   <tr>
                  <th>#</th>
                  <th>Name</th>
                  <th>Description</th>
                  <th>Id</th>
                  <th>Credits</th>
                  <th>Code</th>
                 </tr>
                 </thead>
              <tbody>
                <% @courses.each do |course| %>
                <tr>
                  <td><%= course['id']%> </td>
                  <td><%= course['name']%></td>
                  <td><%= course['description']%></td>
                  <td><%= course['unique_id']%></td>
                  <td><%= course['credits']%></td>
                  <td><%= course['code']%></td>
                </tr>
                  <% end %>
              </tbody>
            </table>
          </div>
</p>

app/views/others/instructors.html.erb
<h1>Instructors</h1>
<p>
<div class="table-responsive">
  <table class="table table-striped">
                 <thead>
                   <tr>
                  <th>#</th>
                  <th>Last</th>
                  <th>Middle</th>
                  <th>First</th>
                  <th>id</th>
                  <th>email</th>
                 </tr>
                 </thead>
              <tbody>
                <% @instructors.each do |instructor| %>
                <tr>
                  <td><%= instructor['id']%> </td>
                  <td><%= instructor['last']%></td>
                  <td><%= instructor['middle']%></td>
                  <td><%= instructor['first']%></td>
                  <td><%= instructor['unique_id']%></td>
                  <td><%= instructor['email']%></td>
                </tr>
                  <% end %>
              </tbody>
            </table>
          </div>
</p>

app/views/others/search.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-12">
            <div class="input-group" id="adv-search">
              <form action="/searchCourse" method="GET" >
                  <br><br><br>
                <input type="text" class="form-control" name="course" placeholder="Search for Course" />
                <br><br><br>
                Subject
                <select class="form-control" name = "subject">
                  <option value = "Filter by Subjects"> Filter by Subjects </option>
                  <% @subjects.each do |d| %>
                  <option value = "<%=d['unique_id']%>" > <%= d['name']%></option>
                  <% end %>
                </select>

                <br><br><br>
                <button type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-search"></span></button>

              </form>
                </div>
            </div>
          </div>
        </div>
	</div>
</div>

app/views/others/subjects.html.erb
<h1>Subjects</h1>
<p>
<div class="table-responsive">
  <table class="table table-striped">
                 <thead>
                   <tr>
                  <th>#</th>
                  <th>Name</th>
                  <th>Abbreviation</th>
                  <th>Id</th>
                 </tr>
                 </thead>
              <tbody>
                <% @subjects.each do |subject| %>
                <tr>
                  <td><%= subject['id']%> </td>
                  <td><%= subject['name']%></td>
                  <td><%= subject['abbr']%></td>
                  <td><%= subject['unique_id']%></td>
                </tr>
                  <% end %>
              </tbody>
            </table>
          </div>
</p>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/help.html.erb
<h1>help</h1>
<p>Home - Display user info (Profile Page) </p>
<p>Subjects - Displays all the subjects from the database</p>
<p>Courses - Displays all the courses from the database</p>
<p>Instructors - Displays all the instructors from the database</p>

app/views/static_pages/main.html.erb
<div class="center jumbotron">
  <h1>Welcome to the Course Catalog</h1>
  </br>
   <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
</div>

app/views/users/_enroll.html.erb
<%= form_for(@user.active_enrollments.build) do |f| %>
  <div><%= hidden_field_tag :course_id, course['id']%></div>
  <%= f.submit "Enroll", class: "btn btn-primary" %>
<% end %>

app/views/users/_unenroll.html.erb
<%= form_for(@user.active_enrollments.find_by(course_id: course['id']),
             html: { method: :delete }) do |f| %>
  <%= f.submit "Unenroll", class: "btn" %>
<% end %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
  <%= form_for(@user, url: signup_path) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/searchCourse.html.erb
<h1>Search Results</h1>
<p>
<div class="table-responsive">
  <table class="table table-striped">
                 <thead>
                   <tr>
                  <th>#</th>
                  <th>Name</th>
                  <th>Description</th>
                  <th>Credits</th>
                  <th>Code</th>
                  <th> Enroll </th>
                 </tr>
                 </thead>
              <tbody>
                <% @searchcourses.each do |course| %>
                <tr>
                  <td><%= course['id']%> </td>
                  <td><%= course['name']%></td>
                  <td><%= course['description']%></td>
                  <td><%= course['credits']%></td>
                  <td><%= course['code']%></td>
                  <td>
  <div id="enroll_form">
  <% if @user.enroll?(course) %>
  <%= form_for(@user.active_enrollments.find_by(course_id: course['id']),
               html: { method: :delete }) do |f| %>
    <%= f.submit "Unenroll", class: "btn" %>
  <% end %>

  <% else %>
  <%= form_for(@user.active_enrollments.create) do |f| %>
    <div><%= hidden_field_tag :course_id, course['id']%></div>
    <%= f.submit "Enroll", class: "btn btn-primary" %>
  <% end %>
  <% end %>
  </div>
  <td>
                </tr>
                  <% end %>
              </tbody>
            </table>
          </div>
</p>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<body>
  <div class="container">
      <div class="row">
          <div class="col-xs-12 col-sm-6 col-md-6">
              <div class="well well-sm">
                  <div class="row">
                      <div class="col-sm-6 col-md-4">
                          <img src="https://case.edu/medicine/admissions/media/school-of-medicine/admissions/classprofile.png" alt="" class="img-rounded img-responsive" />
                      </div>
                      <div class="col-sm-6 col-md-8">
                          <h4>
                              Username:
                               <%= @user.name %> </h4>

                                 </div>
                               </p>

                      </div>
                  </div>
              </div>
          </div>
      </div>
  </div>
  <h1>Enrolled Courses</h1>
  <p>
  <div class="table-responsive">
    <table class="table table-striped">
                   <thead>
                     <tr>
                    <th>#</th>
                    <th>Name</th>
                    <th>Description</th>
                    <th>Id</th>
                    <th>Credits</th>
                    <th>Code</th>
                   </tr>
                   </thead>
                <tbody>
                  <% @courses.each do |course| %>
                  <tr>
                    <td><%= course['id']%> </td>
                    <td><%= course['name']%></td>
                    <td><%= course['description']%></td>
                    <td><%= course['unique_id']%></td>
                    <td><%= course['credits']%></td>
                    <td><%= course['code']%></td>
                  </tr>
                    <% end %>
                </tbody>
              </table>

</body>